### ISSUE TITLE
Stored field value without sortable index

### ISSUE THREAD

**Issue by darl** [yandex/yoctodb#33]
Add option to store field values to index without creating Sortable index.

**Comment by incubos** [comment]
Do you think that stored field values should be optional so that some documents might skip them?
Is it alright to return an empty `Buffer` in this case.
An alternative is to enforce a single stored field value in each document as in the case of sortable fields.

**Comment by incubos** [comment]
Payloads are deprecated in favor of stored fields, but still supported.
Released 0.0.19.
