### ISSUE TITLE
Allow unsafe reading fields as primitives

### ISSUE THREAD

**Issue by ya-goodfella** [yandex/yoctodb#39]
Currently, you may read a primitive value from memory only as getField().getInt, which internally allocates new sliced Buffer. We may introduce new methods

```
byte getFieldAsByteUnsafe
short getFieldAsShortUnsafe
int getFieldAsIntUnsafe
long getFieldAsLongUnsafe
```

and so on for primitive types to avoid allocating parasite objects.
They may throw an exception if a size of data for the document is insufficient for reading.

**Comment by sanekas** [comment]
I take this

**Comment by ya-goodfella** [comment]
@sanekas is on the duty on this one.
